
#repos:
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: ["--line-length=120"]
        files: "\\.py$"

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1  # Check latest version
    hooks:
      - id: nbqa-flake8
        args: ["--max-line-length=120"]  
        files: "\\.ipynb$" 
      - id: nbqa-black
        args: ["--line-length=120"]
        files: "\\.ipynb$"

  - repo: https://github.com/psf/black
    rev: 23.1.0  # Check for the latest version
    hooks:
      - id: black
        args: ["--line-length", "120"] 
  
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
          - --preserve-cell-metadata
          - tags
          - slideshow
          - --
        exclude: "^.*/data/.*$"