name: book
channels:
- conda-forge
- nodefaults
dependencies:
- codespell >=2.4.1,<3
- jupyter-book >=1,<2
- nb-clean >=4.0.1,<5
- papermill >=2.5.0,<3
- pre-commit >=4.2.0,<5
- aiohttp >=3.11.13,<4
- distributed <2024.12.0
- cf_xarray >=0.10.4,<0.11
- contextily >=1.6.2,<2
- flox >=0.10.1,<0.11
- geopandas >=1.0.1,<2
- geoviews-core >=1.14.0,<2
- hvplot >=0.11.2,<0.12
- ipykernel >=6.29.5,<7
- jupyterlab >=4.3.5,<5
- jupyterlab-myst >=2.4.2,<3
- matplotlib-base >=3.10.0,<4
- numpy >=2.2.3,<3
- pandas >=2.2.3,<3
- planetary-computer >=1.0.0,<2
- pyarrow >=19.0.1,<20
- pystac >=1.12.1,<2
- pystac-client >=0.8.6,<0.9
- requests >=2.32.3,<3
- rich >=13.9.4,<14
- rioxarray >=0.18.2,<0.19
- scipy >=1.15.2,<2
- stackstac >=0.5.1,<0.6
- xarray >=2025.3.0,<2026
- xvec >=0.3.1,<0.4
- zarr <3
