name: book
channels:
- conda-forge
- nodefaults
dependencies:
- jupyter-book >=1,<2
- codespell >=2.4.1,<3
- cf_xarray >=0.10.0,<0.11
- contextily >=1.6.2,<2
- geopandas >=1.0.1,<2
- hvplot >=0.11.2,<0.12
- jupyterlab >=4.3.5,<5
- matplotlib-base >=3.10.0,<4
- numpy >=2.2.3,<3
- pandas >=2.2.3,<3
- planetary-computer >=1.0.0,<2
- pystac >=1.12.1,<2
- pystac-client >=0.8.6,<0.9
- requests >=2.32.3,<3
- rioxarray >=0.18.2,<0.19
- scipy >=1.15.2,<2
- stackstac >=0.5.1,<0.6
- xarray >=2025.1.2,<2026
- zarr <3
- jupyterlab-myst >=2.4.2,<3
