# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Cloud-native geospatial datacube workflows with open-source tools
author: Emma Marshall
#logo: logo.png

collapse_inactive_sections: true
#only want to include files listed in toc
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'force'
  allow_errors: true
  timeout: 1500


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/e-marshall/itslive  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"
  notebook_interface: "jupyterlab"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  announcement: > 
    🚧 Feb 2025 - This book is under construction! 🚧


parse:
  myst_enable_extensions:
    - substitution
sphinx:
  config:
    myst_heading_anchors: 3
    myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

    myst_substitutions:
      part1_title: "Background"
      #part2_title: "ITS_LIVE ice velocity data tutorial"
      part2_title: "Using Xarray to examine cloud-based glacier surface velocity data"
      #part3_title: "Sentinel-1 RTC imagery tutorial"
      part3_title:  "Sentinel-1 RTC data workflows with xarray"
      part4_title: "Summary + Conclusion"

      #tutorial 1 nb titles
      title_its_nb1: "# 1. Accessing cloud-hosted ITS_LIVE data"
      title_its_nb2: "# 2. Working with larger than memory data"
      title_its_nb3: "# 3. Handling raster and vector data"
      title_its_nb4: "# 4. Exploratory data analysis of a single glacier"
      title_its_nb5: "# 5. Exploratory data analysis of multiple glaciers"

      #tutorial 2 nb titles
      title_s1_1_1: "# 1. Read Sentinel-1 data processed by ASF"
      title_s1_1_2: "# 2. Inspect and organize S1 data processed by ASF"
      title_s1_1_3: "# 3. Read and inspect Sentinel-1 data processed by Microsoft Planetary Computer"
      title_s1_2_1: "# 4. Comparing Sentinel-1 datasets"
      title_s1_2_2: "# 5. Example of Sentinel-1 RTC time series analysis"

      #global nb sections
      intro: "## Introduction"
      overview: "### Overview"
      outline: "### Outline"
      learning_goals: "### Learning goals"
      concepts: "#### Concepts"
      techniques: "#### Techniques"
      conclusion: "## Conclusion"
      break: "----"

      #nb1
      #can't get subs + links to headings to work
      # so not using lettered headings for now
      # but still using numbered subsections (a1_...)
      a_its_nb1: "A. Overview of ITS_LIVE data"
      a1_its_nb1: "1) Data structure overview"
      a2_its_nb1: "2) Climate Forecast (CF) Metadata Conventions"

      b_its_nb1: "B. Read ITS_LIVE data from AWS S3 using Xarray"
      b1_its_nb1: "1) Overview of ITS_LIVE data storage and catalog"
      b2_its_nb1: "2) Read ITS_LIVE data from S3 storage into memory"
      b3_its_nb1: "3) Check spatial footprint of data"

      c_its_nb1: "C. Query ITS_LIVE catalog"
      c1_its_nb1: "1) Find ITS_LIVE granule for a point of interest"
      c2_its_nb1: "2) Read + visualize spatial footprint of ITS_LIVE data"


      #nb2
      a_its_nb2: "A. Compare approaches for reading larger than memory data"
      a1_its_nb2: "1) `chunks = 'auto'`"
      a2_its_nb2: "2) `chunks = {}`"
      a3_its_nb2: "3) An out-of-order time dimensions"
      a4_its_nb2: "4) Read the dataset without Dask"
      b_its_nb2: "B. Organize data once it's in memory"
      b1_its_nb2: "1) Arrange dataset in chronological order"
      b2_its_nb2: "2) Convert to a Dask-backed `Xarray.Dataset`"

      #nb3 
      a_its_nb3: "Read data using strategy identified in previous notebook"
      b_its_nb3: "Incorporate glacier outline (vector) data"
      b1_its_nb3: "1) Read and reproject vector data"
      b2_its_nb3: "2) Visualize spatial extents of glacier outlines and ITS_LIVE data cube"
      b3_its_nb3: "3) Crop vector data to spatial extent of raster data"
      c_its_nb3: "C. Combine raster and vector data"
      c1_its_nb3: "1) Use vector data to crop raster data"
      c2_its_nb3: "2) Write clipped raster data cube to disk"
      
      #nb4
      a_its_nb4: "A. Data exploration"
      a1_its_nb4: "1) Load raster data and visualize with vector data"
      a2_its_nb4: "2) Examine data coverage along the time dimension"
      a3_its_nb4: "3) Look at data by sensor"
      b_its_nb4: "B. Comparing different satellites"
      b1_its_nb4: "1) DataTree approach"
      b2_its_nb4: "2) GroupBy approach"
      c_its_nb4: "C. Examine velocity variability"
      c1_its_nb4: "1) Histograms and summary statistics"
      c2_its_nb4: "2) Spatial velocity variablity"
      c3_its_nb4: "3) Temporal velocity variability"
      d_its_nb4: "D. Dimensional computations"
      d1_its_nb4: "1) Temporal resampling"
      d2_its_nb4: "2) Grouped analysis by season"
    
      #nb5
      a_its_nb5: "A. Read and organize data"
      a1_its_nb5: "1) Raster data"
      a2_its_nb5: "2) Vector data"

      b_its_nb5: "B. Combine raster and vector to create a vector data cube"
      b1_its_nb5: "1) Make a vector data cube"
      b2_its_nb5: "2) Add attribute data to vector cube"
      b3_its_nb5: "3) Write vector cube to disk"

      c_its_nb5: "C. Data visualization"
      c1_its_nb5: "1) Read vector data cube into memory"
      c2_its_nb5: "2) Visualize velocity data"
      c3_its_nb5: "3) Visualize associations between velocity and attribute data"


      #1_1 section headings
      a_s1_nb1: "A. Setup"
      a1_s1_nb1: "1) Helper functions"
      a2_s1_nb1: "2) Vector data"
      
      b_1_1: "B. Organize data on disk to create VRT objects"





#  extra_extensions:
#  - sphinxext.opengraph
#  config:
#    ogp_site_url: "https://e-marshall.github.io/itslive/intro.html"
#    ogp_image: "https://e-marshall.github.io/itslive/_static/itslive_explore_img.png"
#    ogp_description_length: 200
