#use for building book
name: geospatial_datacube_book_env
channels:
  - conda-forge
  - pkgs/main
  - pyviz
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accessible-pygments=0.0.5
  - affine=2.4.0
  - aiobotocore=2.5.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.10.5
  - aioitertools=0.12.0
  - aiosignal=1.3.2
  - alabaster=0.7.16
  - annotated-types=0.7.0
  - anyio=3.7.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - asciitree=0.3.3
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=21.4.0
  - aws-c-auth=0.7.7
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.8
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.14
  - aws-c-io=0.13.36
  - aws-c-mqtt=0.9.10
  - aws-c-s3=0.4.1
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.7
  - aws-sdk-cpp=1.11.182
  - babel=2.16.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - blosc=1.21.4
  - bokeh=3.1.1
  - boost-cpp=1.78.0
  - botocore=1.29.76
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.33.0
  - ca-certificates=2025.1.31
  - cachetools=5.3.0
  - cairo=1.16.0
  - cartopy=0.23.0
  - certifi=2024.12.14
  - cf_xarray=0.10.0
  - cffi=1.15.1
  - cfitsio=4.2.0
  - cftime=1.6.2
  - charset-normalizer=3.4.1
  - click=8.1.8
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.3
  - contextily=1.6.2
  - contourpy=1.0.7
  - cryptography=40.0.2
  - curl=8.4.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2025.1.0
  - dask-core=2025.1.0
  - dataclasses=0.8
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2025.1.0
  - docutils=0.17.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.5.0
  - fasteners=0.19
  - fiona=1.9.4
  - flox=0.10.0
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freexl=1.0.6
  - frozenlist=1.4.1
  - fsspec=2023.5.0
  - gdal=3.7.0
  - geographiclib=2.0
  - geopandas=0.13.0
  - geopandas-base=0.13.0
  - geopy=2.4.1
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.6.0
  - greenlet=3.0.3
  - hdf4=4.2.15
  - hdf5=1.14.1
  - holoviews=1.16.2
  - hvplot=0.8.4
  - icu=72.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.6.1
  - importlib_metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.23.1
  - ipython=8.13.2
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.5
  - jmespath=1.0.1
  - joblib=1.4.2
  - json-c=0.16
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter-cache=0.6.1
  - jupyter-lsp=2.1.0
  - jupyter_bokeh=4.0.5
  - jupyter-book=1.0.3
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.1
  - jupyterlab_widgets=3.0.13
  - kealib=1.5.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - latexcodec=2.0.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.0.6
  - libarchive=3.6.2
  - libarrow=14.0.1
  - libarrow-acero=14.0.1
  - libarrow-dataset=14.0.1
  - libarrow-flight=14.0.1
  - libarrow-flight-sql=14.0.1
  - libarrow-gandiva=14.0.1
  - libarrow-substrait=14.0.1
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.4.0
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgdal=3.7.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.3
  - libgomp=12.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libopenblas=0.3.21
  - libparquet=14.0.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.44.2
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.11.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - linkify-it-py=2.0.0
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.2
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.3.5
  - mdurl=0.1.0
  - mercantile=1.2.1
  - mistune=2.0.5
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munch=3.0.0
  - munkres=1.1.4
  - nbclient=0.7.4
  - nbconvert-core=7.4.0
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - netcdf4=1.6.4
  - networkx=3.1
  - nodejs=20.5.1
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89
  - numcodecs=0.11.0
  - numpy=1.24.3
  - numpy_groupies=0.9.22
  - openjpeg=2.5.0
  - openssl=3.1.6
  - orc=1.9.2
  - packaging=23.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - panel=1.2.0
  - param=1.13.0
  - parso=0.8.3
  - partd=1.4.0
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - planetary-computer=1.0.0
  - pooch=1.7.0
  - poppler=23.05.0
  - poppler-data=0.4.12
  - postgresql=15.3
  - proj=9.2.1
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.1
  - pybtex=0.24.0
  - pybtex-docutils=1.0.2
  - pycparser=2.21
  - pyct=0.5.0
  - pyct-core=0.5.0
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydata-sphinx-theme=0.15.4
  - pygments=2.15.1
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyproj=3.6.0
  - pyrsistent=0.19.3
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pystac=1.12.1
  - pystac-client=0.8.6
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.17.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - pyviz_comms=0.7.6
  - pyyaml=6.0
  - pyzmq=25.0.2
  - rasterio=1.3.8
  - rdma-core=28.9
  - re2=2023.09.01
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rioxarray=0.18.2
  - rtree=1.0.1
  - runthis-sphinxext=0.0.3
  - s2n=1.3.56
  - s3fs=2023.5.0
  - scikit-learn=1.2.2
  - scipy=1.14.0
  - send2trash=1.8.2
  - setuptools=67.7.2
  - shapely=2.0.1
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=2.0.15
  - sqlite=3.42.0
  - stack_data=0.6.2
  - stackstac=0.5.1
  - tabulate=0.9.0
  - tblib=1.7.0
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tiledb=2.13.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.6.1
  - typing_extensions=4.6.1
  - tzcode=2023c
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - ucx=1.15.0
  - urllib3=1.26.15
  - watermark=2.3.1
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.2
  - wheel=0.40.0
  - widgetsnbextension=4.0.13
  - wrapt=1.15.0
  - xarray=2024.10.0
  - xerces-c=3.2.4
  - xvec=0.3.1
  - xyzservices=2023.5.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.1
  - zarr=2.18.4
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.6
  # For book
  - myst-nb=1.1.2
  - myst-parser=1.0.0
  - mystmd=1.3.23
  - sphinx=5.3.0
  - sphinx-book-theme=1.1.3
  - sphinx-comments=0.0.3
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.6.1
  - sphinx-external-toc=1.0.1
  - sphinx-jupyterbook-latex=1.0.0
  - sphinx-multitoc-numbering=0.1.3
  - sphinx-thebe=0.3.1
  - sphinx-togglebutton=0.3.2
  - sphinxcontrib-applehelp=1.0.4
  - sphinxcontrib-bibtex=2.5.0
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31

  - pip:
    - geoviews==1.10.0
    - pre_commit==4.1.0
    - sphinxext-opengraph==0.8.2
    - xmode==0.6.1


